### ISSUE TITLE
Clicking on "Give feedback" will not show up again

### ISSUE THREAD

**Issue by jrcacd** [Pixplicity/gene-rate#19]

**Comment by echopros** [comment]
hi. would you please help me. i canno't install it correctly, can you show me what did you import to your mainactivity ??
i imported 
import com.pixiplicity.generate.rate 
... ?? i have some symbols that can't be resolved
thx in advance

**Comment by mlagerberg** [comment]
@jrcacd What exactly is the expected behaviour? Once the user has clicked 'give feedback', Gene-rate will indeed never ask again, for it assumes the user has provided feedback and is done with that. We cannot check whether the user as actually gone through with giving feedback, but we prefer to nag as little as possible.

@echopros Your comment is unrelated to this issue and should be asked elsewhere.
